podnet: 10.244.0.0/16

kubernetes_version: "1.18.0"
# For versions: https://github.com/kubernetes/kubernetes/releases

docker_ce_version: "19.03.8~ce~3-0~raspbian"
# For available versions: https://docs.docker.com/engine/release-notes/

flannel_version: "master"
# v0.10.0
# v0.9.1
# v0.9.0
# v0.8.0
# v0.7.1
# v0.7.0