- hosts: all
  roles:
    - role: common
      tags: ['install']
    - role: kubeadm
      tags: ['install']

- hosts: master
  vars_files:
    - vars/secrets.yml
  roles:
    - role: master
      tags: ['reset', 'create']
    - role: dashboard
      tags: ['create']

- hosts: nfs
  vars_files:
      - vars/nfs.yml
  roles:
    - role: nfs
      tags: ['create']

- hosts: all:!master
  vars_files:
    - vars/secrets.yml
  roles:
    - role: workers
      tags: ['join', 'create']