- hosts: all
  roles:
    - role: common
      tags: ['prepare']
    - role: kubeadm
      tags: ['prepare', 'setup']

- hosts: master
  vars_files:
    - vars/secrets.yml
  roles:
    - role: master
      tags: ['join']
    - role: dashboard
      tags: ['install']

- hosts: all:!master
  roles:
    - role: workers
      tags: ['join']