---
- name: Ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname
  tags: hostname

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ advertise_address|default(ansible_default_ipv4.address) }}.+$"
    line: "{{ advertise_address|default(ansible_default_ipv4.address) }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  register: hostname
  tags: hostname

- name: set timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"
  when: timezone is defined
  register: tz

# - name: gpu mem check
#   shell: cat /boot/config.txt | grep gpu_mem
#   changed_when: false
#   register: gpu_mem_check

# - name: reduce gpu memory
#   lineinfile:
#     path: /boot/config.txt
#     line: gpu_mem=16
#   register: gpu_mem
#   when: gpu_mem_check.stdout == ""

- name: Enabling cgroup options at boot
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  when: ansible_lsb.id == "Raspbian" # https://github.com/debops/debops-tools/issues/187
  register: cmdline
  tags:
    - boot

- name: apt-get update
  apt:
    force_apt_get: yes # https://github.com/ansible/ansible/issues/56832
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: apt-get upgrade
  apt:
    force_apt_get: yes # https://github.com/ansible/ansible/issues/56832
    upgrade: full

- name: python-apt dependency
  shell: apt-get install -y python-apt
  args:
    warn: no

- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible Reboot"
  async: 1
  poll: 0
  ignore_errors: True
  register: reboot
  when: hostname is changed or (tz is defined and tz is changed) or (cmdline is defined and cmdline is changed)

- name: Wait for Reboot
  local_action: wait_for
  args:
    host: "{{ ansible_default_ipv4.address }}"
    port: 22
    delay: 15
    timeout: 120
  become: False
  when: hostname is changed or (tz is defined and tz is changed) or (cmdline is defined and cmdline is changed)
